name: Testing
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.1.0  
    - name: Test on k3s
      run: |
        make init
