name: Testing
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.4.0

    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.0.1

    - name: Run chart-testing (list-changed)
      id: list-changed
      run: |
        changed=$(ct list-changed --chart-dirs cijenkinsio)
        if [[ -n "$changed" ]]; then
          echo "::set-output name=changed::true"
        fi

    - name: Run chart-testing (lint)
      run: ct lint

    - name: Create Kind Cluster
      uses: helm/kind-action@v1.1.0
      if: steps.list-changed.outputs.changed == 'true'  

    - name: Build Chart
      run: helm dependency build cijenkinsio
      if: steps.list-changed.outputs.changed == 'true'  

    - name: Deploy Chart
      run: helm upgrade --install cijenkinsio cijenkinsio
      if: steps.list-changed.outputs.changed == 'true'  

    - name: Test Chart
      run: helm test cijenkinsio
      if: steps.list-changed.outputs.changed == 'true'  
